import type { MetricRow } from "../types";

const r = (
  department: string,
  category: string,
  lineItem: string,
  units: MetricRow["units"],
  isEditable: boolean,
  aggMethod: MetricRow["aggMethod"],
  assignee = ""
): MetricRow => ({
  department,
  category,
  id: `${department} ${lineItem}`,
  lineItem,
  units,
  assignee,
  isEditable,
  aggMethod,
});

const PD = "Product Development";
const MK = "Marketing";
const SA = "Sales";
const CS = "Customer Success";
const FI = "Finance";

export const METRIC_DEFS: MetricRow[] = [

  // ── Product Development ───────────────────────────────────────────────────
  // Categories from Actuals/Budget: Squads, Production, Story Point Breakout %, Efficiency
  r(PD, "Squads",                 "# of Squads",                           "#", true,  "EoP",     "Engineering"),
  r(PD, "Squads",                 "# of Sprints",                          "#", true,  "Sum",     "Engineering"),
  r(PD, "Production",             "Story Points Committed",                "#", true,  "Sum",     "Engineering"),
  r(PD, "Production",             "Story Points Completed",                "#", true,  "Sum",     "Engineering"),
  r(PD, "Production",             "% Completed",                           "%", false, "Average", "Engineering"),
  r(PD, "Story Point Breakout %", "Product",                               "%", true,  "Average", "Engineering"),
  r(PD, "Story Point Breakout %", "Maintenance / Internal",                "%", true,  "Average", "Engineering"),
  r(PD, "Efficiency",             "Headcount (Total)",                     "#", false, "EoP",     "Engineering"),
  r(PD, "Efficiency",             "Headcount - Squad - Onshore",           "#", true,  "EoP",     "Engineering"),
  r(PD, "Efficiency",             "Headcount - Squad - Offshore",          "#", true,  "EoP",     "Engineering"),
  r(PD, "Efficiency",             "Headcount - Non-Squad",                 "#", true,  "EoP",     "Engineering"),
  r(PD, "Efficiency",             "Avg. Personnel Cost per Squad",         "$", true,  "Average", "Finance"),
  r(PD, "Efficiency",             "P&T Overhead",                          "$", true,  "Sum",     "Finance"),

  // ── Marketing ─────────────────────────────────────────────────────────────
  // Categories from Actuals/Budget: New Leads Generated, Effectiveness,
  //   Pipeline & Revenue, Content Engagement by Channel (Actuals) / Lead Generation (Budget), Efficiency
  r(MK, "New Leads Generated",    "Marketing Qualified Leads",             "#", true,  "Sum",     "Marketing"),
  r(MK, "New Leads Generated",    "(x) MQL to New Opp. Conversion %",     "%", true,  "Average", "Marketing"),
  r(MK, "New Leads Generated",    "= Mktg sourced New Opportunities",     "#", false, "Sum",     "Marketing"),
  r(MK, "Effectiveness",          "Mktg sourced New Opportunities",       "#", true,  "Sum",     "Marketing"),
  r(MK, "Effectiveness",          "(x) Mktg sourced New Opp. ACV",        "$", true,  "Average", "Marketing"),
  r(MK, "Effectiveness",          "= Mktg sourced New Opp. Value",        "$", false, "Sum",     "Marketing"),
  r(MK, "Effectiveness",          "(x) Expected Win Rate",                "%", true,  "Average", "Marketing"),
  r(MK, "Effectiveness",          "= Expected Revenue of New Opp.",       "$", false, "Sum",     "Marketing"),
  r(MK, "Pipeline & Revenue",     "Mktg sourced pipeline, EoP",           "$", true,  "EoP",     "Marketing"),
  r(MK, "Pipeline & Revenue",     "Mktg sourced Won ARR",                 "$", true,  "Sum",     "Marketing"),
  r(MK, "Lead Generation",        "Leads - Digital (Paid)",               "#", true,  "Sum",     "Marketing"),
  r(MK, "Lead Generation",        "Leads - Digital (Organic)",            "#", true,  "Sum",     "Marketing"),
  r(MK, "Lead Generation",        "Leads - Events / Conferences",         "#", true,  "Sum",     "Marketing"),
  r(MK, "Lead Generation",        "Leads - Outbound (BDR)",               "#", true,  "Sum",     "Marketing"),
  r(MK, "Lead Generation",        "Leads - Other",                        "#", true,  "Sum",     "Marketing"),
  r(MK, "Lead Generation",        "Spend - Digital (Paid)",               "$", true,  "Sum",     "Marketing"),
  r(MK, "Lead Generation",        "Spend - Digital (Organic)",            "$", true,  "Sum",     "Marketing"),
  r(MK, "Lead Generation",        "Spend - Events / Conferences",         "$", true,  "Sum",     "Marketing"),
  r(MK, "Lead Generation",        "Spend - Outbound (BDR)",               "$", true,  "Sum",     "Marketing"),
  r(MK, "Lead Generation",        "Spend - Other",                        "$", true,  "Sum",     "Marketing"),
  r(MK, "Efficiency",             "Headcount",                            "#", true,  "EoP",     "Finance"),
  r(MK, "Efficiency",             "Mktg expense",                         "$", true,  "Average", "Finance"),
  r(MK, "Efficiency",             "Mktg exp. per $1 ARR",                 "$", false, "Average", "Finance"),

  // ── Sales ─────────────────────────────────────────────────────────────────
  // Categories from Actuals/Budget: Sales ARR ($), Pipeline Activity (in-period),
  //   Pipeline Value (EoP) by Stage, Pipeline Count (EoP) by Stage,
  //   Pipeline Weeks by Stage, Lost + Nurtured by Stage, Efficiency
  r(SA, "Sales ARR ($)",                 "New Logo ARR ($)",                    "$", true,  "Sum",     "Sales"),
  r(SA, "Pipeline Activity (in-period)", "Sales Generated Opps.",               "#", true,  "Sum",     "Sales"),
  r(SA, "Pipeline Activity (in-period)", "Marketing Generated Opps.",           "#", true,  "Sum",     "Sales"),
  r(SA, "Pipeline Activity (in-period)", "Referral Generated Opps.",            "#", true,  "Sum",     "Sales"),
  r(SA, "Pipeline Activity (in-period)", "New Pipeline Opportunities",          "#", false, "Sum",     "Sales"),
  r(SA, "Pipeline Activity (in-period)", "Won",                                 "#", true,  "Sum",     "Sales"),
  r(SA, "Pipeline Activity (in-period)", "Lost + Nurture",                      "#", true,  "Sum",     "Sales"),
  r(SA, "Pipeline Activity (in-period)", "Win rate: Total",                     "#", false, "Average", "Sales"),
  r(SA, "Pipeline Activity (in-period)", "Avg ACV",                             "$", true,  "Average", "Sales"),
  r(SA, "Pipeline Activity (in-period)", "Avg Age of Opps Won in Period",       "#", true,  "Average", "Sales"),
  r(SA, "Pipeline Value (EoP) by Stage", "EoP Value - Early Stage",             "$", true,  "EoP",     "Sales"),
  r(SA, "Pipeline Value (EoP) by Stage", "EoP Value - Intermediate Stage",      "$", true,  "EoP",     "Sales"),
  r(SA, "Pipeline Value (EoP) by Stage", "EoP Value - Advanced Stage",          "$", true,  "EoP",     "Sales"),
  r(SA, "Pipeline Value (EoP) by Stage", "EoP Value - Total",                   "$", false, "EoP",     "Sales"),
  r(SA, "Pipeline Count (EoP) by Stage", "EoP Count - Early Stage",             "#", true,  "EoP",     "Sales"),
  r(SA, "Pipeline Count (EoP) by Stage", "EoP Count - Intermediate Stage",      "#", true,  "EoP",     "Sales"),
  r(SA, "Pipeline Count (EoP) by Stage", "EoP Count - Advanced Stage",          "#", true,  "EoP",     "Sales"),
  r(SA, "Pipeline Count (EoP) by Stage", "EoP Count - Total",                   "#", false, "EoP",     "Sales"),
  r(SA, "Pipeline Weeks by Stage",       "Pipeline Weeks - Early",              "#", true,  "Average", "Sales"),
  r(SA, "Pipeline Weeks by Stage",       "Pipeline Weeks - Intermediate",       "#", true,  "Average", "Sales"),
  r(SA, "Pipeline Weeks by Stage",       "Pipeline Weeks - Advanced",           "#", true,  "Average", "Sales"),
  r(SA, "Lost + Nurtured by Stage",      "Lost + Nutured - Early",              "#", true,  "Sum",     "Sales"),
  r(SA, "Lost + Nurtured by Stage",      "Lost + Nutured - Intermediate",       "#", true,  "Sum",     "Sales"),
  r(SA, "Lost + Nurtured by Stage",      "Lost + Nutured - Advanced",           "#", true,  "Sum",     "Sales"),
  r(SA, "Lost + Nurtured by Stage",      "Lost + Nutured - Total",              "#", false, "Sum",     "Sales"),
  r(SA, "Efficiency",                    "Headcount",                           "#", true,  "EoP",     "Finance"),
  r(SA, "Efficiency",                    "Sales expense",                       "$", true,  "Average", "Finance"),
  r(SA, "Efficiency",                    "Sales exp. per $1 ARR",               "$", false, "Average", "Finance"),

  // ── Customer Success ───────────────────────────────────────────────────────
  // Categories from Actuals/Budget: ARR ($), Client Activity (#),
  //   Client Satisfaction (#) [contains both Renewals and NPS items], C.S. Efficiency
  r(CS, "ARR ($)",              "Cross-sell",                                  "$", true,  "Sum",     "CS"),
  r(CS, "ARR ($)",              "Upsell",                                      "$", true,  "Sum",     "CS"),
  r(CS, "ARR ($)",              "Price",                                       "$", true,  "Sum",     "CS"),
  r(CS, "ARR ($)",              "Total Gross Growth",                          "$", false, "Sum",     "CS"),
  r(CS, "ARR ($)",              "(-) Churn",                                   "$", true,  "Sum",     "CS"),
  r(CS, "ARR ($)",              "Total Net Growth",                            "$", false, "Sum",     "CS"),
  r(CS, "ARR ($)",              "Gross Growth %",                              "%", false, "Average", "CS"),
  r(CS, "ARR ($)",              "Churn %",                                     "%", false, "Average", "CS"),
  r(CS, "ARR ($)",              "NRR %",                                       "%", false, "Average", "CS"),
  r(CS, "Client Activity (#)",  "# of Clients",                               "#", true,  "EoP",     "CS"),
  r(CS, "Client Activity (#)",  "Reference Clients",                          "#", true,  "EoP",     "CS"),
  r(CS, "Client Activity (#)",  "Churned Clients",                            "#", true,  "Sum",     "CS"),
  r(CS, "Client Activity (#)",  "# Growth Clients (up/cross sold + price)",   "#", true,  "Sum",     "CS"),
  r(CS, "Client Activity (#)",  "# Renewed Clients",                          "#", true,  "Sum",     "CS"),
  r(CS, "Client Satisfaction (#)", "ARR up for Renewal",                      "$", true,  "EoP",     "CS"),
  r(CS, "Client Satisfaction (#)", "% of Total",                              "%", false, "Average", "CS"),
  r(CS, "Client Satisfaction (#)", "Obtainment",                              "$", true,  "EoP",     "CS"),
  r(CS, "Client Satisfaction (#)", "NRR on Renewal",                          "%", false, "Average", "CS"),
  r(CS, "Client Satisfaction (#)", "Very Satisfied Clients (NPS 9-10)",       "#", true,  "EoP",     "CS"),
  r(CS, "Client Satisfaction (#)", "Satisfied Clients (NPS 7-8)",             "#", true,  "EoP",     "CS"),
  r(CS, "Client Satisfaction (#)", "Dissatisfied Clients (NPS 5-6)",          "#", true,  "EoP",     "CS"),
  r(CS, "Client Satisfaction (#)", "At-Risk Clients (NPS <4)",                "#", true,  "EoP",     "CS"),
  r(CS, "Client Satisfaction (#)", "NPS Estimate",                            "#", false, "Average", "CS"),
  r(CS, "C.S. Efficiency",      "Headcount",                                  "#", true,  "EoP",     "Finance"),
  r(CS, "C.S. Efficiency",      "C.S. upsell / cross-sell ARR",               "$", false, "Sum",     "CS"),
  r(CS, "C.S. Efficiency",      "C.S. expense",                               "$", true,  "Sum",     "Finance"),
  r(CS, "C.S. Efficiency",      "C.S. exp. per $1 ARR",                       "$", false, "Average", "Finance"),

  // ── Finance ───────────────────────────────────────────────────────────────
  // Categories from Actuals/Budget: Income Statement Items, Balance Sheet Items,
  //   Other, Zero-Based Budgeting, Rule of 200
  r(FI, "Income Statement Items", "ARR",                                      "$", true,  "EoP",     "Finance"),
  r(FI, "Income Statement Items", "Revenue",                                  "$", true,  "Sum",     "Finance"),
  r(FI, "Income Statement Items", "(-) Service/Delivery (CoS/CoGS)",         "$", true,  "Sum",     "Finance"),
  r(FI, "Income Statement Items", "(-) Product",                             "$", true,  "Sum",     "Finance"),
  r(FI, "Income Statement Items", "(-) Technology",                          "$", true,  "Sum",     "Finance"),
  r(FI, "Income Statement Items", "(-) Sales",                               "$", true,  "Sum",     "Finance"),
  r(FI, "Income Statement Items", "(-) Marketing",                           "$", true,  "Sum",     "Finance"),
  r(FI, "Income Statement Items", "(-) Customer Success",                    "$", true,  "Sum",     "Finance"),
  r(FI, "Income Statement Items", "(-) G&A",                                 "$", true,  "Sum",     "Finance"),
  r(FI, "Income Statement Items", "Adj. EBITDA",                             "$", false, "Sum",     "Finance"),
  r(FI, "Income Statement Items", "Other (Severance, Legal, etc.)",          "$", true,  "Sum",     "Finance"),
  r(FI, "Balance Sheet Items",    "Debt & Debt-like Items",                  "$", true,  "EoP",     "Finance"),
  r(FI, "Balance Sheet Items",    "(-) Cash",                                "$", true,  "EoP",     "Finance"),
  r(FI, "Balance Sheet Items",    "Net Debt",                                "$", false, "EoP",     "Finance"),
  r(FI, "Other",                  "Total Headcount",                         "#", false, "EoP",     "Finance"),
  r(FI, "Other",                  "Employees",                               "#", true,  "EoP",     "Finance"),
  r(FI, "Other",                  "VeArc",                                   "#", true,  "EoP",     "Finance"),
  r(FI, "Other",                  "3rd Party Providers",                     "#", true,  "EoP",     "Finance"),
  r(FI, "Zero-Based Budgeting",   "Avg. Personnel Cost per Squad",           "$", false, "Average", "Finance"),
  r(FI, "Zero-Based Budgeting",   "P&T Overhead",                            "$", false, "Sum",     "Finance"),
  r(FI, "Zero-Based Budgeting",   "Mktg exp. per $1 ARR",                    "$", false, "Average", "Finance"),
  r(FI, "Zero-Based Budgeting",   "Sales exp. per $1 ARR",                   "$", false, "Average", "Finance"),
  r(FI, "Zero-Based Budgeting",   "C.S. exp. per $1 ARR",                    "$", false, "Average", "Finance"),
  r(FI, "Rule of 200",            "New Logo ARR Growth (annualized)",         "%", false, "EoP",     "Finance"),
  r(FI, "Rule of 200",            "NRR (annualized)",                         "%", false, "EoP",     "Finance"),
  r(FI, "Rule of 200",            "Gross Margin",                             "%", false, "Average", "Finance"),
  r(FI, "Rule of 200",            "EBITDA Margin",                            "%", false, "Average", "Finance"),
  r(FI, "Rule of 200",            "Score",                                    "",  false, "Average", "Finance"),
  r(FI, "Rule of 200 (YTD)",      "New Logo ARR Growth (YTD)",                "%", false, "EoP",     "Finance"),
  r(FI, "Rule of 200 (YTD)",      "NRR (YTD)",                                "%", false, "EoP",     "Finance"),
  r(FI, "Rule of 200 (YTD)",      "Gross Margin (YTD)",                       "%", false, "Average", "Finance"),
  r(FI, "Rule of 200 (YTD)",      "EBITDA Margin (YTD)",                      "%", false, "Average", "Finance"),
  r(FI, "Rule of 200 (YTD)",      "Score (YTD)",                              "",  false, "Average", "Finance"),
];
